### ISSUE TITLE
How to save augmented image to the file?

### ISSUE THREAD

**Issue by John1231983** [Prasad9/ImageAugmentationTypes#1]
Hello, thanks so much for the great tutorial. It is very useful for me
I am using your code to augment my dataset that has about 300 images. I will augment it to 30000 images and save it to tfrecord file (using [`build_image_data.py`](https://github.com/tensorflow/models/blob/master/research/inception/inception/data/build_image_data.py) in tensorflow model). I have two options to do it:

1. I will generate 30000 images and save it to file, then just call the function `build_image_data.py`.
2. Incorporate your code to the `build_image_data.py` and I don't need to save the image to file. 

I think the first option looks easier. Could you tell me which function will be good to save your augmented image to PNG file? Thanks

**Comment by Prasad9** [comment]
Hi @John1231983 
I am glad that my tutorial has helped you. 
Regarding the way in which you would like to generate the tfrecord file entirely depends upon you. I will just list the pros and cons with both the methods:
**Method 1**:  With this you will have advantage of going through the generated images. If you find that some of the generated image has lost the meaning for the label of the image, you have the advantage of deleting that particular image and keeping your dataset more relevant. Also, the code of `build_image_data.py` is readily available to operate on saved images files directly. Only disadvantage I am seeing is that it will consume your disk space for 30000 images.
**Method 2**: Suppose you are experimenting heavily with the dataset you are generating and you need to keep generating tfrecord file again and again to suit your purpose, then bypassing one step of saving and then generating tfrecord step will help you in saving time. For this however, you will have to modify the code in `build_image_data.py` to operate directly on data and not saved files. You can start working on this from [_convert_to_example](https://github.com/tensorflow/models/blob/master/research/inception/inception/data/build_image_data.py#L118) method which accepts image data.

If you are new to this field, I would suggest you to go with first method for now.

To save image in png format you can make use of [imsave](https://matplotlib.org/api/image_api.html#matplotlib.image.imsave) function something like this:
```
import matplotlib.image as mpimg
mpimg.imsave("<my_file_name>.png", <image_data>)
```

Do let me know if this solves your doubt.

**Comment by John1231983** [comment]
Thanks so much for your comments. I have followed the first method. It is reading from a tfrecord file that contains the original file, then i will extract the image from it and perform augmentation, such as scaling as you did, but it shows a wrong scaling image, and tf section is always reset. Could you look at my full code and give me some advice. This is full code. 

https://gist.github.com/John1231983/c458a79abdb9fe55f50fb871f2de12d4

I know that your original code support the an array images as input, but my above function just return a single image, thus, I was slightly modified it

**Comment by Prasad9** [comment]
Hi @John1231983, I couldn't run your code because of some dependencies. So you may have to help me out a little more by telling exactly what problem are you getting, like the error message or the image you got and image you were expecting etc. 
However, looking into scaling part of code, I can say that [line 56](https://gist.github.com/John1231983/c458a79abdb9fe55f50fb871f2de12d4#file-read_record_and_aug-py-L56) in your gist is not needed. Next, please can you print the `shape` of `scaled_imgs` in line 55. It should be [1, 224, 224, 3].

**Comment by John1231983** [comment]
Thanks. You can find some dependence file athttps://github.com/yeephycho/tensorflow_input_image_by_tfrecord/tree/master/src

The main problem is that your scaling code also call reset section and run section, while my main function also call it. It looks that we call it twice time and the result my produces a wrong output

**Comment by John1231983** [comment]
hello, I have updated the code. it can work now but the output is not expected. could you check the new version of the code? Thanks

**Comment by Prasad9** [comment]
Hi @John1231983 , I ran the code with the dependencies and simulating the type of tfrecord file with necessary keys. I believe you are talking about you are getting a totally blurred (garbage type) of output when you are saving the image (Apart from that, I didn't find any other specific bug in your code). If that is the case, replace the following lines in your gist

```
scaled_imgs = sess.run(tf_img, feed_dict={X: batch_img})
print (scaled_imgs.shape)
scaled_imgs=Image.fromarray(scaled_imgs[0,:,:,:], "RGB")
scaled_imgs.save(os.path.join("./resized_image", os.path.splitext(os.path.basename(pre_filename))[0]+"_" + "scaling" + ".png"))
```

with

```
scaled_imgs = sess.run(tf_img, feed_dict={X: batch_img})
print (scaled_imgs.shape)
mpimg.imsave(os.path.join("./resized_image", os.path.splitext(os.path.basename(pre_filename))[0]+"_" + "scaling" + ".png"), scaled_imgs[0])
```

Don't forget to import matplotlib.image as
`
import matplotlib.image as mpimg `

Please close the issue if this is resolving your issue.

**Comment by John1231983** [comment]
Thank you, I was used the code as you suggest but it is still showing an unexpected result as

![12163418275_bd6a1edd61_scaling](https://user-images.githubusercontent.com/24875971/33050260-40b55064-cea7-11e7-9fc6-b8d41d6f44a5.png)
 
This is the [tfrecord](https://drive.google.com/drive/folders/0BwTYOWiLy2btX2RiZHlDYVdiWVE?usp=sharing) file that obtained from flower dataset. And I updated the code as you mentioned in the https://gist.github.com/John1231983/c458a79abdb9fe55f50fb871f2de12d4

**Comment by Prasad9** [comment]
I ran the train.tfrecord example file provided by you with your sample code. The problem is in values aren't scaled from 0.0 to 1.0 while saving using `imsave` method. Downscale it by 255.0 and then everything should be ok.
So your imsave code should be:
`mpimg.imsave(<file_path>, scaled_imgs[0] / 255.0)`

Let me know if this solves your problem.

**Comment by John1231983** [comment]
Great. It solved my problem. Thanks so much
