### ISSUE TITLE
OpenCV error: Bad Argument in lighting Conditions module

### ISSUE THREAD

**Issue by Xnsam** [Prasad9/ImageAugmentationTypes#2]
Hi,

First of all, you have done a great job, thank you very much for the tutorial examples.

I am trying out your code on my images of dimension 36 x 36... I am stuck at the lighting conditions module.
It gives me this error:
`OpenCV Error: Bad argument (When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified) in arithm_op, file /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/core/src/arithm.cpp, line 663
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: /opt/conda/conda-bld/opencv_1491943970124/work/opencv-3.1.0/modules/core/src/arithm.cpp:663: error: (-5) When the input arrays in add/subtract/multiply/divide functions have different types, the output array type must be explicitly specified in function arithm_op
` 

The error comes in the line cv2.addWeighted()

I tried google search but din't find any answer yet.

It would be really great if could direct whats wrong?

**Comment by Prasad9** [comment]
Hi @Xnsam , Thanks a lot for using my tutorials. 
This is the header of the function `cv2.addWeighted()`:
`cv2.addWeighted(src1, alpha, src2, beta, gamma[, dst[, dtype]]) → dst`

What is happening is that you are passing different `dtype` images in src1 and src2. In my code, I have made src2 as float32, so I believe you are using some integer or float16, 64 etc type of image in src1. 

The solution is you will have to explicitly set the dtype of your output `dst` variable. This code example should help you out:
```
src1 = np.ones((32, 32, 1), dtype = np.int32)
src2 = np.ones((32, 32, 1), dtype = np.float32)
x = cv2.addWeighted(src1, 0.5, src2, 0.5, 0, dtype = cv2.CV_32F)
```
In the above example, if you have not mentioned desired output type of cv2.CV_32F, the code would have returned error.

Do let me know if this has helped you.

**Comment by Xnsam** [comment]
Hi @Prasad9 ,
Thanks for the reply...

Yes , by adding the `dtype=cv2.CV_32F` in the code

`gaussian_img = cv2.addWeighted(X_img, 0.75, 0.25 * gaussian , 0.25,0, dtype=cv2.CV_32F)`

i am using python 3 .5 with opencv 3.1
